### ISSUE TITLE
Tooltips on quantitative bar visualizations are not shown in Firefox

### ISSUE THREAD

**Issue by keller-mark** [hms-dbmi/cistrome-explorer#242]
![Screen Shot 2020-05-18 at 10 00 53 AM](https://user-images.githubusercontent.com/7525285/82221861-8937df00-98ee-11ea-88c3-13507d4918a8.png)

**Comment by sehilyi** [comment]
It looks Firefox is actually showing rows in the proper order since `descending` order of sorting is applied to the bar chart track. This sorting issue in Chrome is related to #216. 

It looks this bug occurs when we call a `.sort()` function multiple times. I think we need to make a one custom sort() function and call it only once in `select-rows.js`.

(https://stackoverflow.com/questions/13211709/javascript-sort-array-by-multiple-number-fields)

**Comment by sehilyi** [comment]
![Screen Shot 2020-05-19 at 10 19 18 AM](https://user-images.githubusercontent.com/9922882/82337850-375c8b00-99ba-11ea-82a8-336a95279b68.png)

It looks Firefox (76.0.1) on my mac properly shows the tooltip. How your browser shows the tooltip?

**Comment by sehilyi** [comment]
In the @keller-mark's browser (Firefox Developer 77.0b1) tooltips are not shown at all sometimes. It looks the hidden canvas is not properly working somehow in the browser.

**Comment by sehilyi** [comment]
I've changed the title to focus only on the tooltip bug here since the sorting issue seems to be duplicated with #216.

**Comment by keller-mark** [comment]
I updated Firefox (to version 78.0b1) yesterday and I think it fixed this bug.
